config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket
    else
      render 'new'
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])

    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
  end

  private
    def ticket_params
      params.require(:ticket).permit(:title, :category, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to "Index_Ticket", tickets_path %>
<%= link_to "New_Ticket", new_ticket_path %>

<%#= link_to "Show_Ticket", ticket_path(:id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Destek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>
<%= form_for @ticket do |t| %>
  <p>
    <%= t.label :title %>
    <%= t.text_field :title %>
  </p>
  <p>
    <%= t.label :category %>
    <%= t.text_field :category %>
  </p>
  <p>
    <%= t.label :content %>
    <%= t.text_area :content %>
  </p>
  <p>
    <%= t.submit %>
<% end %>

app/views/tickets/index.html.erb
<h1>Listing Tickets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.title %></td>
      <td><%= ticket.category %></td>
      <td><%= ticket.content %></td>
    </tr>
  <% end %>
</table>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>
<%= form_for @ticket do |t| %>
  <p>
    <%= t.label :title %> <br />
    <%= t.text_field :title %>
  </p>
  <p>
    <%= t.label :category %> <br />
    <%= t.text_field :category %>
  </p>
  <p>
    <%= t.label :content %> <br />
    <%= t.text_area :content %>
  </p>
  <p>
    <%= t.submit %>
  </p>
<% end %>

app/views/tickets/show.html.erb
<h1>Title: <%= @ticket.title %></h1>
<p> Category: <%= @ticket.category %></p>
<p> Content: <%= @ticket.content %></p>
<%= link_to "Edit_Ticket", edit_ticket_path(@ticket) %>